### ISSUE TITLE
[hyperproxy-browser] Duplicates data being sent through WebRTC peer

### ISSUE THREAD

**Issue by louisgv** [goonism/hyperproxy#4]
BUG

### Expected Behavior

Peer sending data only once.

### Current Behavior

When sending data from one peer to another, the data being sent is duplicated.

### Possible Solution

Check the subscribed hub.

### Your Environment

| software         | version(s)
| ---------------- | -------
| node             | 9.8.0
| npm              | 5.6.0
| Operating System | Linux Mint

**Comment by ColdSauce** [comment]
@louisgv when you push your commit, can you reference it here and close this issue? Thanks

**Comment by louisgv** [comment]
Closed with #9
